### ISSUE TITLE
Cannot import and use schemato

### ISSUE THREAD

**Issue by tadas-subonis** [Parsely/schemato#18]
Hi, 

I am importing schemato like this:
```
from schemato.schemato import Schemato
from schemato.distillery import ParselyDistiller
```

this doesn't work as well:
```
from schemato import Schemato
```

However, I am getting this error:
```
  File "C:\Python33-64bit\lib\site-packages\xxxxxxxxx\html.py", line 9, in <module>
    import schemato
  File "C:\Python33-64bit\lib\site-packages\schemato\__init__.py", line 1, in <module>
    from schemato import Schemato
ImportError: cannot import name Schemato
```

**Comment by emmett9001** [comment]
Hi, thanks for filing this ticket.

How did you install Schemato? If you used `pip install schemato`, it's possible that the package on PyPI is out of date. Please clone this repository and use `python setup.py develop` in a fresh environment to see if that fixes the issue.

**Comment by tadas-subonis** [comment]
Yes - I've used pip.

On Fri, Mar 20, 2015 at 6:22 PM, Emmett J. Butler <notifications@github.com>
wrote:

> Hi, thanks for filing this ticket.
>
> How did you install Schemato? If you used pip install schemato, it's
> possible that the package on PyPI is out of date. Please clone this
> repository and use python setup.py develop in a fresh environment to see
> if that fixes the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Parsely/schemato/issues/18#issuecomment-84060268>.
>



-- 

Kind Regards,
Tadas Šubonis

**Comment by emmett9001** [comment]
from schemato import Schemato
should work with [version 1.3.0](https://pypi.python.org/pypi?:action=display&name=schemato&version=1.3.0). You can try `pip install schemato --upgrade`.
